- package-lock.json
- package.json
Before v3 `disparity` had a dependency on an insecure version of `diff`. You can see that detailed in the `magento-eslint` [security alert](https://github.com/magento-research/magento-eslint/network/alert/package-lock.json/diff/open).
This bumps the version of `disparity` to one that has a fixed version of diff.
Note: Because `mocha` used a fixed version of diff, there was no alert for this repo.
> Updates disparity dep to version with updated diff dependency

- README.md
> docs: fix valid-package-def link in README.md

- README.md
Since the package was transferred to me, I want to make sure @zetlen is credited somewhere more visible than the historical contributors page. 😄
> docs: note @zetlen as creator in README.md

- lib/processors/PackageJsonProcessor.js
- tests/lib/processors/PackageJsonProcessor.js
> fix: detect package.json in Windows

- tests/lib/rules/valid-local-dependency.js
Fixes #60.
The problem was the `invalid` cases weren't giving errors when the resolved path differed from file system casing. Requested paths like `.../Valid-local-dependency` were passing when the file case on system was `.../valid-local-dependency`. I played a bit with adding explicit logic to check for case sensitivity but:
* That can get complicated
* Not all operating systems are case sensitive by default
...so this instead switches the tests to use paths that differ in more than just casing.
> chore: switch valid-local-dependency tests to not rely on file system casing

- src/index.ts
- src/tests/index.test.ts
-   [x] Addresses an existing open issue: fixes #102
This PR fixes `"plugin:package-json/recommended"` to work and adds a test case to check the fix.
> fix: recommended config

- README.md
- docs/rules/order-properties.md
- docs/rules/sort-collections.md
- docs/rules/valid-local-dependency.md
- docs/rules/valid-package-def.md
-   [x] Addresses an existing open issue: fixes #110
Regenerates the table following #103.
```shell
pnpm run update:eslint-docs                                                                            
```
> docs: regenerate eslint-doc-generator table

- README.md
- docs/rules/order-properties.md
- docs/rules/sort-collections.md
- docs/rules/valid-local-dependency.md
- docs/rules/valid-package-def.md
- src/rules/valid-package-def.ts
-   [x] Addresses an existing open issue: fixes #112; fixes #113
Touches up the README.md to better explain itself and no longer reference a global installation.
Also applies a bit of polish to rule docs:
* Applies [sentences-per-line](https://github.com/JoshuaKGoldberg/sentences-per-line) manually
* Lower-cases npm instead of NPM
* General phrasing and such
> docs: touchups

- docs/rules/order-properties.md
- src/rules/order-properties.ts
- src/tests/rules/order-properties.test.ts
-   [x] Addresses an existing open issue: fixes #58
Applies the change, along with a notice in the docs.
**This is a breaking change**. But since this package is still 0.x, there's nothing necessary to do with semver.
> feat: change order-properties order default to sort-package-json

- README.md
- docs/rules/valid-repository-directory.md
- src/index.ts
- src/rules/prefer-repository-shorthand.ts
- src/rules/valid-repository-directory.ts
- src/tests/rules/valid-repository-directory.test.ts
- src/utils/findJSONLiteralWithValue.ts
- src/utils/findPropertyWithKeyValue.ts
-   [x] Addresses an existing open issue: fixes #53
Equivalent to `json-files/ensure-repository-directory`. Renamed to `valid-*` to match the precedent of the existing rules `valid-package-def` and `valid-package-dependency`.
Re-uses the `findJSONLiteralWithValue` utility and renames it to the more appropriate `findPropertyWithKeyValue`
> feat: added valid-repository-directory rule

- README.md
-   [x] Addresses an existing open issue: fixes #46
Mentions [`prettier-plugin-packagejson`](https://github.com/matzkoh/prettier-plugin-packagejson) and that these tools synergize nicely. _Synergy!_
Also applies a [sentences-per-line](https://github.com/JoshuaKGoldberg/sentences-per-line) touchup I'd been meaning to for a while.
> docs: mentioned prettier-plugin-packagejson

- README.md
- docs/rules/unique-dependencies.md
- src/index.ts
- src/rules/unique-dependencies.ts
- src/tests/rules/unique-dependencies.test.ts
- src/utils/predicates.ts
-   [x] Addresses an existing open issue: fixes #50
I ended up naming it `unique-dependencies` because I'm not a fan of `no-` prefixes for lint rules (https://github.com/typescript-eslint/typescript-eslint/discussions/6022).
> feat: added unique-dependencies rule

- src/rules/order-properties.ts
- src/tests/index.test.ts
- src/tests/rules/order-properties.test.ts
- src/tests/rules/ruleTester.ts
-   [x] Addresses an existing open issue: fixes #127; fixes #128
Fixes #127 by providing a default `filename` for `invalid` and `valid` cases. Also fixes #128's discovered issues as a result.
> fix: correct order-properties key checks

- README.md
- docs/rules/valid-name.md
- package.json
- pnpm-lock.yaml
- src/index.ts
- src/rules/valid-name.ts
- src/tests/rules/valid-name.test.ts
-   [x] Addresses an existing open issue: fixes #131
Adds the rule using the same `validate-npm-package-name` dependency as `npm-package-json-lint`.
> feat: added valid-name rule

- README.md
- docs/rules/valid-version.md
- package.json
- pnpm-lock.yaml
- src/index.ts
- src/rules/valid-version.ts
- src/tests/rules/valid-version.test.ts
-   [x] Addresses an existing open issue: fixes #130
Adds the rule using the standard `semver` package used by `npm-package-json-lint`.
> feat: added valid-version rule

- docs/rules/sort-collections.md
-   [x] Addresses an existing open issue: fixes #136
Deactivation of the sorting rule so that the incorrect example remains incorrect after linting.
🌱
> fix: incorrect example in 'sort-collections'

- src/createRule.ts
- src/utils/isPackageJson.test.ts
- src/utils/isPackageJson.ts
-   [x] Addresses an existing open issue: fixes #142
Re-applies #30 to the `main` branch.
> fix: support Windows paths, again

- src/rules/valid-package-def.ts
- src/tests/rules/valid-package-def.test.ts
-   [x] Addresses an existing open issue: fixes #251
pnpm has a "workspace protocol" (link) that allows you to explicitly say a package lives in your current workspace. Ignore this when doing package.json validation by adding `workspace` to the ignore glob.
> fix(valid-package-def): ignore pnpm workspace protocol

- src/rules/valid-name.ts
- src/tests/rules/valid-name.test.ts
-   [x] Addresses an existing open issue: fixes #000
When I write a project that is not a npm package, we do not need to make the name field match the npm package rules.
Sorry for not creating an issue first(I am lazy), feel free to close this PR if you do not want to make this change.
> fix: skip check for name to match npm package when private is true

- cspell.json
- package.json
- pnpm-lock.yaml
- src/rules/valid-repository-directory.ts
- src/tests/rules/valid-repository-directory.test.ts
-   [x] Fixes #252
There are two commits:
~1. "settings" - these are just ignores I'm adding to keep my local development environment out of this project (e.g. I use devbox to manage my tool chain, so I'm ignoring those files from the repo)~
2. "fix ..." - the actual lint rule fixes
The code changes here aren't that big because we're leaning on my [@altano/repository-tools](https://www.npmjs.com/package/@altano/repository-tools) library to do the hardest part: …
> fix(valid-repository-directory): use repository root for more accurate linting

- docs/rules/sort-collections.md
- src/rules/sort-collections.ts
- src/tests/rules/sort-collections.test.ts
Added sorting `exports` in `package.json`.
Fail:
```json
"exports": {
"./package.json": "./package.json"
".": {
"import": "./dist/index.mjs",
"require": "./dist/index.js",
"types": "./dist/index.d.ts"
},
},
```
Pass:
```json
"exports": {
".": {
"import": "./dist/index.mjs",
"require": "./dist/index.js",
"types": "./dist/index.d.ts"
},
"./package.json": "./package.json"
},
```
> fix: add sorting exports field

- README.md
- docs/rules/unique-dependencies.md
- src/rules/unique-dependencies.ts
-   [x] Addresses an existing open issue: fixes #529
Adds docs for `unique-dependencies` rule
> Favourite emoji: 🥘
> docs: add unique dependencies rule

- README.md
-   [x] Addresses an existing open issue: fixes #49
Moves any mention of installing `jsonc-eslint-parser` to just within the _Legacy Config_ section.
💖
> docs: fix jsonc-eslint-parser installation instructions

- README.md
-   [x] Addresses an existing open issue: fixes #661
Add a `Development` section in the README for better discoverability.
> docs: add `Development` section in README

- src/rules/sort-collections.ts
-   [x] Addresses an existing open issue: fixes #619
-   [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/blob/main/.github/CONTRIBUTING.md) were taken 😊
Adds `overrides` to the `defaultCollections`. Note that tests were not added because `dependencies`/`devDependencies`/`peerDependencies` are currently not tested.
> feat(sort-collections): should sort `overrides`

- cspell.json
- src/rules/sort-collections.ts
- src/tests/rules/sort-collections.test.ts
-   [x] Addresses an existing open issue: fixes #499
Fixes #499 and adds tests 😄 
I'm not 100% sold on how I did the implementation, and I'm curious to know your thoughts on it.
> feat: sort alphabetically with co-located hooks for `scripts`

- .eslintrc.cjs
- package.json
- pnpm-lock.yaml
- src/rules/order-properties.ts
- src/rules/repository-shorthand.ts
- src/rules/sort-collections.ts
- src/rules/unique-dependencies.ts
- src/rules/valid-local-dependency.ts
- src/rules/valid-name.ts
- src/rules/valid-package-def.ts
- src/rules/valid-repository-directory.ts
- src/rules/valid-version.ts
-   [x] Addresses an existing open issue: fixes #82 
This change adds the `eslint-plugin-eslint-plugin` recommended config to the project's lint configuration, and disables the current 25 errors, for addressing as follow-up changes.
Closes #82
> build: add eslint-plugin plugin to project's lint config

- README.md
- docs/rules/no-redundant-files.md
- eslint.config.js
- src/plugin.ts
- src/rules/no-redundant-files.ts
- src/tests/rules/no-redundant-files.test.ts
-   [x] Addresses an existing open issue: fixes #686 
This change adds a new rule for preventing inclusion of unnecessary or redundant files in a package.json's `files` list.  It checks for two primary types of errors:
1. Duplicate entries within the files array (the same file listed more than once)
1. Files that are automatically included by npm, and don't need to be explicitly included.
Of the second type, there are two flavors that npm includes automatically …
> feat(no-redundant-files): add new rule

- src/utils/isPackageJson.test.ts
-   [ ] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/blob/main/.github/CONTRIBUTING.md) were taken
I had developed some vscode extensions. I will add some json files like `package.nls.json` or `package.nls.zh-cn.json` for internationalization support. So I add more test cases.
> test: add more test cases for isPackageJson function

- .release-it.json
This change backports this update to CTA: https://github.com/JoshuaKGoldberg/create-typescript-app/pull/1810  reducing the categories that release-it shows in changelog updates.
> ci: update release config to hide non-user-facing categories

- README.md
- docs/rules/no-empty-fields.md
- src/plugin.ts
- src/rules/no-empty-fields.ts
- src/tests/rules/no-empty-fields.test.ts
- src/utils/predicates.ts
-   [x] Addresses an existing open issue: fixes #683
> feat: add no-empty-fields rule

- package.json
- pnpm-lock.yaml
- src/rules/no-empty-fields.ts
- src/rules/no-redundant-files.ts
- src/rules/unique-dependencies.ts
- src/tests/rules/no-empty-fields.test.ts
-   [x] Addresses an existing open issue: fixes #747
Uses the exported APIs added in https://github.com/JoshuaKGoldberg/eslint-fix-utils/commit/6bf5c3329eb47c43d38128328fd4501277b3c8ad.
@michaelfaith I'd love to get your input on this: how does the API feel to you? If you think they should be changed drastically -here and/or in the other repo- I'm definitely up for iterating on them. 🙂 
~~The build failures can be ignored, they're some problem in …
> chore: use `eslint-fix-utils` for element and property removals

- src/rules/no-redundant-files.ts
- src/tests/rules/no-redundant-files.test.ts
-   [x] Addresses an existing open issue: fixes #763 
This change detects additional variations of `README` and `LICENSE` files.  Apparently, npm will include any `README` followed by any extension (e.g. `README.fi.md`)
Closes #763
> fix(no-redundant-files): detect variations of README.md as redundant

- src/rules/valid-local-dependency.ts
-   [x] Addresses an existing open issue: fixes #118 
This change removes an unreachable code block.  `require.resolve` will only return a string, if the file is resolvable, or throw an error if it isn't.  There's never a case in which `require.resolve` would return a falsy value.
Closes #118
> refactor(valid-local-dependency): remove unreachable code

- .release-it.json
- pnpm-lock.yaml
This change adjusts the release it config so that the output generated from the changelog plugin is used for the github release page.
I discussed this here https://github.com/release-it/release-it/issues/1025#issuecomment-2617948522, and @webpro theorized it was the autoGenerate that overrode the changelog output.
I created a test repo to verify and confirmed that that did, indeed, fix the issue: …
> ci: fix the release it config to only show user-facing changes

- package.json
> chore: remove unnecessary files from package.json files field

- README.md
- docs/rules/require-author.md
- package.json
- src/plugin.ts
- src/rules/require-properties.ts
- src/tests/rules/require-author.test.ts
- src/utils/createRequirePropertyRule.ts
-   [x] Addresses an existing open issue: fixes #795 
This change adds the first or our new `require-` rules, and creates some foundational plumbing to make it super easy to add new require rules.  I've only done author in this PR.  Assuming this all looks good, we can quickly knock all the rest of the require rules in one shot.
> feat(require-author): add new `require-author` rule

- .github/renovate.json
This change updates our renovate config to extend the recommended, which will include all monorepo and recommended groups.  E.g. grouping vitest updates with @vitest/* updates.
> ci: extend renovate recommended config

- README.md
- docs/rules/require-name.md
- src/rules/require-properties.ts
- src/tests/rules/require-name.test.ts
-   [x] Addresses an existing open issue: fixes #808 
Add `require-name` rule.
> feat(require-name): add require-name rule

- README.md
- docs/rules/require-keywords.md
- src/rules/require-properties.ts
- src/tests/rules/require-keywords.test.ts
-   [x] Addresses an existing open issue: fixes #866 
Add `require-keywords` rule
> feat(require-keywords): add require-keywords rule

- README.md
- docs/rules/require-files.md
- src/rules/require-properties.ts
- src/tests/rules/require-files.test.ts
-   [x] Addresses an existing open issue: fixes #803 
Add `require-files` rule
> feat(require-files): add require-files rule

- .github/workflows/lint-eslint-docs.yml
- package.json
This change adds a build pre-step to the eslint doc update script.  There's never really a case where you'd not want to have a build happen when running the doc update command, and when running locally, it's not super obvious that it's necessary to run a build first.  Baking it into the update script removes that ambiguity.
> chore: add build pre-step to doc update rule

- README.md
- docs/rules/require-engines.md
- src/rules/require-properties.ts
- src/tests/rules/require-engines.test.ts
-   [x] Addresses an existing open issue: fixes #868 
This change adds a new `require-engines` rule.
> feat(require-engines): add new rule

- README.md
- docs/rules/require-types.md
- src/rules/require-properties.ts
- src/tests/rules/require-types.test.ts
-   [x] Addresses an existing open issue: fixes #816
This change adds a new `require-types` rule.
Closes #816
> feat(require-types): add new rule

- src/rules/valid-package-definition.ts
This change removes unnecessary error ignore patterns.  These are supported in package-json-validator
> refactor(valid-package-definition): remove unnecessary exclusions

- src/rules/no-redundant-files.ts
- src/tests/rules/no-redundant-files.test.ts
Fixed a crash in the `no-redundant-files` rule when `files` contains wildcard patterns (like `*.d.ts`) and a `main` field is present.
- Added wildcard detection to `getCachedLocalFileRegex` function
- Files with glob patterns (`*`, `?`, `[]`, `{}`, `**`, `!`) are now skipped during validation
- Regular files continue to be validated normally for redundancy
- Added comprehensive test coverage for wildcard patterns
The rule now gracefully handles package.json files with glob patterns while maintaining all existing validation for regular file paths.
> fix: prevent `no-redundant-files` crash with wildcard and `main` field

- .github/workflows/ci.yml
- docs/rules/valid-package-def.md
- docs/rules/valid-package-definition.md
- package.json
- pnpm-lock.yaml
- src/plugin.ts
- src/rules/valid-package-definition.ts
- src/tests/rules/valid-package-definition.test.ts
This change adds a new `ignoreProperties` option to the `valid-package-definition` rule, allowing you to provide a list of top-level properties to suppress violation reports for.  This can be useful when using this rule alongside any of the more granular `valid-*` rules, so that it's not double reporting violations.
> feat(valid-package-definition): add ignoreProperties option

- cspell.json
- package.json
Correcting the `package.json` `author` also removed the excess `zetlan` from the `cspell.json` `words`. I removed a bunch more by:
1. Deleting it
2. Running `npx cspell-populate-words "**" ".github/**"`
🗂️
> chore: correct author attribution and reset cspell words

- README.md
- docs/rules/valid-bin.md
- docs/rules/valid-name.md
- docs/rules/valid-version.md
- src/plugin.ts
- src/rules/valid-bin.ts
- src/tests/rules/valid-bin.test.ts
This change adds a new `valid-bin` rule that uses `validateBin` from `package-json-validator` to identify errors.
This will need to wait to merge after #1077, so that we're not double-reporting validation errors on `bin` with `valid-package-definition`.
Lastly, this is the first new rule that employs our new approach of using the more granular validation functions from `package-json-validator` and can serve as a model for the rest of the `valid-*` rules.
> feat(valid-bin): add new rule for validating bin

- README.md
- docs/rules/valid-bin.md
- package.json
- pnpm-lock.yaml
- src/rules/valid-bin.ts
- src/tests/rules/valid-bin.test.ts
This change adds a new option to the `valid-bin` rule, that enforces that, when the `bin` value is an object, the keys of the object (representing the commands for each script) are formatted as kebab-case.   Violations for this include editor suggestions for converting the key to kebab case.
> feat(valid-bin): add option for enforcing kebab-case

- README.md
This change adds a "Deprecation Policy" section to our README.
@JoshuaKGoldberg recommended also including an RFC / Consideration period (https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues/1119#issuecomment-3000597078), which I've incorporated.  He'd thrown out the idea of 3 months.  That felt a little long for an RFC period.  I generally see RFCs wrapping up within a month or two.  I put it at 6 weeks (which felt good against 6 month removal period).  But happy to go with something in the middle.  Let me know what you think.
> docs: define deprecation policy

- README.md
- docs/rules/valid-bundleDependencies.md
- src/plugin.ts
- src/rules/valid-bundleDependencies.ts
- src/tests/rules/valid-bundleDependencies.test.ts
This change adds a new `valid-bundleDependencies` rule that uses `validateBundleDependencies` from package-json-validator to identify errors.
> feat(valid-bundleDependencies): add new rule for validating `bundleDependencies`

- README.md
- docs/rules/valid-license.md
- package.json
- pnpm-lock.yaml
- src/plugin.ts
- src/rules/valid-license.ts
- src/tests/rules/valid-license.test.ts
This change adds a new `valid-license` rule that uses `validateLicense` from package-json-validator to identify errors.
> feat(valid-license): add new rule for validating `license`

- .github/workflows/ci.yml
- src/rules/valid-repository-directory.ts
- src/tests/rules/valid-repository-directory.test.ts
This change addresses an issue with `valid-repository-directory` where the rule assumed users would always be in a posix environment.  The logic didn't account for windows path separators being different.  Now, at the end, we're swapping whatever separator the system is using with posix path separator.
I also updated our test ci steps to also run all tests on windows, in addition to what we already had (ubuntu).
> fix(valid-repository-directory): use correct path separator when on windows

- README.md
- docs/rules/valid-config.md
- src/plugin.ts
- src/rules/valid-config.ts
- src/tests/rules/valid-config.test.ts
This change adds a new `valid-config` rule that uses `validateConfig` from package-json-validator to identify errors.  It's included in the `recommended` config.
> feat(valid-config): add new rule for validating `config`

- docs/rules/no-empty-fields.md
- src/rules/no-empty-fields.ts
- src/tests/rules/no-empty-fields.test.ts
* An "ignoreProperties" option is added to the `no-empty-fields` rule to specify top-level properties to ignore.
* I considered ignoring the immediate property name instead, but that seemed too likely to lack context.
* I considered allowing for "paths", like "browserslist.developement", to ignore only certain subproperties. But then we'd probably need to allow for wildcards and arrays of objects, and that seemed overly complex when the immediate need is satisfied by naming only the top-level property.
* Tests are added to verify correct behavior of the new option.
* Documentation is updated to document the new option.
🗂
> feat(no-empty-fields): Add `ignoreProperties` option

- src/rules/no-empty-fields.ts
- src/tests/rules/no-empty-fields.test.ts
This change fixes an issue with `no-empty-fields` where it errors out if the `package.json` consists of just an empty object (or array).
> fix(no-empty-fields): don't throw error on empty object

- README.md
- docs/rules/valid-dependencies.md
- docs/rules/valid-devDependencies.md
- docs/rules/valid-optionalDependencies.md
- docs/rules/valid-peerDependencies.md
- package.json
- pnpm-lock.yaml
- src/rules/valid-properties.ts
- src/tests/rules/valid-dependencies.test.ts
- src/tests/rules/valid-devDependencies.test.ts
- src/tests/rules/valid-optionalDependencies.test.ts
- src/tests/rules/valid-peerDependencies.test.ts
- fixes #822 
- fixes #824
- fixes #833 
- fixes #835 
This change include four new rules, with each rule broken out by commit.  They're for all four flavors of `dependencies`:
- `valid-dependencies`
- `valid-devDependencies`
- `valid-optionalDependencies`
- `valid-peerDependencies`
> feat(valid-dependencies): add new rule for validating dependencies

- README.md
- docs/rules/require-author.md
- docs/rules/require-bugs.md
- docs/rules/require-bundleDependencies.md
- docs/rules/require-dependencies.md
- docs/rules/require-description.md
- docs/rules/require-devDependencies.md
- docs/rules/require-engines.md
- docs/rules/require-files.md
- docs/rules/require-keywords.md
- docs/rules/require-name.md
- docs/rules/require-optionalDependencies.md
- docs/rules/require-peerDependencies.md
- docs/rules/require-type.md
- docs/rules/require-types.md
- docs/rules/require-version.md
- src/createRule.ts
- src/index.ts
- src/rules/require-properties.ts
- src/tests/rules/require-properties.test.ts
- src/utils/createSimpleRequirePropertyRule.ts
This PR adds `ignorePrivate` option to all `require-*` rules to skip package.json files with `private: true`. It's set to `true` by default only for `require-{name,version}` rules.
@JoshuaKGoldberg [suggested introducing](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues/1092#issuecomment-2976567386) a global option to control the behavior of the rules in case of private packages, but I'm not too sure how it would work.
> feat: add `ignorePrivate` option to all `require-*` rules

- docs/rules/require-bugs.md
- docs/rules/require-bundleDependencies.md
- docs/rules/require-dependencies.md
- docs/rules/require-devDependencies.md
- docs/rules/require-optionalDependencies.md
- docs/rules/require-peerDependencies.md
Coming from https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/pull/1158, after fixing the merge conflict and correcting the docs errors for the PR author (due to me creating the conflict 😬), I realized I didn't update the rule name in these docs when bringing the over from the other rules.
> docs: fix mistake in new require rule docs

- eslint.config.ts
- package.json
- pnpm-lock.yaml
- src/rules/no-empty-fields.ts
- src/rules/order-properties.ts
- src/rules/repository-shorthand.ts
- src/rules/restrict-dependency-ranges.ts
- src/rules/sort-collections.ts
- src/rules/valid-bin.ts
- src/rules/valid-package-definition.ts
This change updates the version of `eslint-plugin-eslint-plugin` to its new major version, and resolves new violations.  This version now has types provided, so I was also able to remove one of the remaining `@ts-expect-error`s in our eslint config.
> chore: update eslint-plugin-eslint-plugin

- package.json
- pnpm-lock.yaml
- src/rules/sort-collections.ts
- src/tests/rules/sort-collections.test.ts
This change updates how we're sorting script properties in `sort-collections`, to align with how  `prettier-plugin-packagejson` sorts it.  The main gap in what we had in our bespoke implementation and what we have now, is that pre/post lifecycle scripts were not being grouped together if the non-prefixed version of the script was not also included.  For example, it's rare to have an `install` script in a package.json, but super common to have a `postinstall`.  Now `preinstall` and `postinstall` are sorted correctly in the place where `install` would normally be sorted, with `preinstall` coming first and `postinstall` coming second.
In order to achieve this, I replaced the bespoke script sorting implementation with a call to `sort-package-json`, which is what the prettier plugin also uses …
> fix(sort-collections): align sorting of scripts with `prettier-plugin-packagejson`

- src/createRule.ts
- src/rules/no-empty-fields.ts
- src/rules/no-redundant-files.ts
- src/rules/order-properties.ts
- src/rules/repository-shorthand.ts
- src/rules/require-properties.ts
- src/rules/restrict-dependency-ranges.ts
- src/rules/sort-collections.ts
- src/rules/unique-dependencies.ts
- src/rules/valid-bin.ts
- src/rules/valid-local-dependency.ts
- src/rules/valid-name.ts
- src/rules/valid-package-definition.ts
- src/rules/valid-properties.ts
- src/rules/valid-repository-directory.ts
- src/rules/valid-version.ts
- src/utils/createSimpleRequirePropertyRule.ts
- src/utils/createSimpleValidPropertyRule.ts
This PR changes the signature of `createRule` which now requires rule name to be passed in order to generate the link to the rule docs.
> feat: add docs url to all rules
